import { FrcTeam, FrcMatch, MatchScoutingEntry, PitScoutingData, PicklistTeam } from '@/types/frc';

export const INITIAL_TEAMS: FrcTeam[] = [
  {
    number: 254,
    name: 'The Cheesy Poofs',
    organization: 'Bellarmine College Preparatory',
    location: 'San Jose, CA',
    rookieYear: 1999,
    epa: 68.4,
    autoEpa: 24.2,
    teleopEpa: 34.0,
    endgameEpa: 10.2,
    rank: 1,
    record: { wins: 11, losses: 1, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team254',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'Active',
  },
  {
    number: 1678,
    name: 'Citrus Circuits',
    organization: 'Davis Senior High School',
    location: 'Davis, CA',
    rookieYear: 2005,
    epa: 65.8,
    autoEpa: 22.8,
    teleopEpa: 33.1,
    endgameEpa: 9.9,
    rank: 2,
    record: { wins: 10, losses: 2, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team1678',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'Queueing',
  },
  {
    number: 118,
    name: 'The Robonauts',
    organization: 'NASA Johnson Space Center / CCISD',
    location: 'Houston, TX',
    rookieYear: 1997,
    epa: 62.5,
    autoEpa: 21.0,
    teleopEpa: 31.8,
    endgameEpa: 9.7,
    rank: 3,
    record: { wins: 9, losses: 3, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team118',
    drivetrain: 'Custom Swerve',
    status: 'Pit Inspection',
  },
  {
    number: 2056,
    name: 'OP Robotics',
    organization: 'Orchard Park Secondary School',
    location: 'Stoney Creek, ON, Canada',
    rookieYear: 2007,
    epa: 61.9,
    autoEpa: 19.5,
    teleopEpa: 32.5,
    endgameEpa: 9.9,
    rank: 4,
    record: { wins: 9, losses: 3, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team2056',
    drivetrain: 'Swerve WCP',
    status: 'Active',
  },
  {
    number: 1323,
    name: 'MadTown Robotics',
    organization: 'Madera High School',
    location: 'Madera, CA',
    rookieYear: 2004,
    epa: 60.1,
    autoEpa: 20.3,
    teleopEpa: 30.1,
    endgameEpa: 9.7,
    rank: 5,
    record: { wins: 8, losses: 4, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team1323',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'On Field',
  },
  {
    number: 2910,
    name: 'Jack in the Bot',
    organization: 'Henry M. Jackson High School',
    location: 'Mill Creek, WA',
    rookieYear: 2009,
    epa: 59.4,
    autoEpa: 21.2,
    teleopEpa: 28.5,
    endgameEpa: 9.7,
    rank: 6,
    record: { wins: 8, losses: 4, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80',
    cadUrl: 'https://cad.onshape.com/documents/team2910',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'Active',
  },
  {
    number: 4414,
    name: 'HighTide',
    organization: 'Ventura Unified School District',
    location: 'Ventura, CA',
    rookieYear: 2022,
    epa: 58.7,
    autoEpa: 20.0,
    teleopEpa: 29.0,
    endgameEpa: 9.7,
    rank: 7,
    record: { wins: 7, losses: 5, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=800&q=80',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'Active',
  },
  {
    number: 971,
    name: 'Spartan Robotics',
    organization: 'Mountain View High School',
    location: 'Mountain View, CA',
    rookieYear: 2002,
    epa: 57.2,
    autoEpa: 19.1,
    teleopEpa: 28.6,
    endgameEpa: 9.5,
    rank: 8,
    record: { wins: 7, losses: 5, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=800&q=80',
    drivetrain: 'Custom Swerve',
    status: 'Active',
  },
  {
    number: 3310,
    name: 'Black Hawk Robotics',
    organization: 'Heath High School',
    location: 'Heath, TX',
    rookieYear: 2010,
    epa: 55.4,
    autoEpa: 18.0,
    teleopEpa: 28.0,
    endgameEpa: 9.4,
    rank: 9,
    record: { wins: 6, losses: 6, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    drivetrain: 'Swerve WCP',
    status: 'Active',
  },
  {
    number: 33,
    name: 'Killer Bees',
    organization: 'Notre Dame Preparatory',
    location: 'Pontiac, MI',
    rookieYear: 1996,
    epa: 54.0,
    autoEpa: 17.5,
    teleopEpa: 27.2,
    endgameEpa: 9.3,
    rank: 10,
    record: { wins: 6, losses: 6, ties: 0 },
    imageUrl: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=800&q=80',
    drivetrain: 'Swerve SDS Mk4i',
    status: 'Active',
  },
];

export const INITIAL_MATCHES: FrcMatch[] = [
  {
    matchNumber: 42,
    compLevel: 'Qualification',
    scheduledTime: '14:15 PM',
    status: 'Completed',
    redAlliance: {
      teams: [254, 2910, 3310],
      score: 118,
      autoScore: 38,
      teleopScore: 56,
      endgameScore: 24,
      coopertition: true,
      rankingPoints: 4,
    },
    blueAlliance: {
      teams: [1678, 118, 971],
      score: 112,
      autoScore: 35,
      teleopScore: 54,
      endgameScore: 23,
      coopertition: true,
      rankingPoints: 2,
    },
    predictedWinner: 'Red',
    predictedWinProb: 0.54,
  },
  {
    matchNumber: 43,
    compLevel: 'Qualification',
    scheduledTime: '14:28 PM',
    status: 'Completed',
    redAlliance: {
      teams: [2056, 4414, 33],
      score: 104,
      autoScore: 32,
      teleopScore: 50,
      endgameScore: 22,
      coopertition: true,
      rankingPoints: 3,
    },
    blueAlliance: {
      teams: [1323, 3310, 254],
      score: 122,
      autoScore: 40,
      teleopScore: 58,
      endgameScore: 24,
      coopertition: true,
      rankingPoints: 4,
    },
    predictedWinner: 'Blue',
    predictedWinProb: 0.63,
  },
  {
    matchNumber: 44,
    compLevel: 'Qualification',
    scheduledTime: '14:40 PM',
    status: 'In Progress',
    redAlliance: {
      teams: [254, 1678, 2056],
      score: 62,
      autoScore: 42,
      teleopScore: 20,
      endgameScore: 0,
      coopertition: false,
    },
    blueAlliance: {
      teams: [118, 1323, 2910],
      score: 55,
      autoScore: 38,
      teleopScore: 17,
      endgameScore: 0,
      coopertition: false,
    },
    predictedWinner: 'Red',
    predictedWinProb: 0.61,
  },
  {
    matchNumber: 45,
    compLevel: 'Qualification',
    scheduledTime: '14:55 PM',
    status: 'Upcoming',
    redAlliance: {
      teams: [971, 4414, 33],
    },
    blueAlliance: {
      teams: [118, 254, 3310],
    },
    predictedWinner: 'Blue',
    predictedWinProb: 0.72,
  },
  {
    matchNumber: 46,
    compLevel: 'Qualification',
    scheduledTime: '15:10 PM',
    status: 'Upcoming',
    redAlliance: {
      teams: [1678, 2910, 2056],
    },
    blueAlliance: {
      teams: [1323, 971, 4414],
    },
    predictedWinner: 'Red',
    predictedWinProb: 0.58,
  },
];

export const INITIAL_SCOUTING_ENTRIES: MatchScoutingEntry[] = [
  {
    id: 'scout-1',
    matchNumber: 42,
    teamNumber: 254,
    scoutName: 'Alex M.',
    alliance: 'Red',
    driverStation: 1,
    autoLeave: true,
    autoCoralL1: 0,
    autoCoralL2: 1,
    autoCoralL3: 2,
    autoCoralL4: 2,
    autoAlgaeProcessor: 1,
    autoAlgaeNet: 0,
    autoMissed: 0,
    teleopCoralL1: 1,
    teleopCoralL2: 2,
    teleopCoralL3: 4,
    teleopCoralL4: 5,
    teleopAlgaeProcessor: 2,
    teleopAlgaeNet: 1,
    cycles: 12,
    defenseRating: 1,
    climbStatus: 'Deep Cage',
    climbTimeSeconds: 4.2,
    diedOrTipped: false,
    cards: 'None',
    driverSkill: 5,
    notes: 'Blazing fast swerve cycles. Seamless L4 coral placement. Quick alignment with dual AprilTag cameras.',
    timestamp: '2026-09-23 14:22:15',
  },
  {
    id: 'scout-2',
    matchNumber: 42,
    teamNumber: 1678,
    scoutName: 'Jessica L.',
    alliance: 'Blue',
    driverStation: 1,
    autoLeave: true,
    autoCoralL1: 0,
    autoCoralL2: 0,
    autoCoralL3: 3,
    autoCoralL4: 2,
    autoAlgaeProcessor: 1,
    autoAlgaeNet: 1,
    autoMissed: 0,
    teleopCoralL1: 0,
    teleopCoralL2: 3,
    teleopCoralL3: 4,
    teleopCoralL4: 4,
    teleopAlgaeProcessor: 3,
    teleopAlgaeNet: 0,
    cycles: 11,
    defenseRating: 2,
    climbStatus: 'Deep Cage',
    climbTimeSeconds: 5.1,
    diedOrTipped: false,
    cards: 'None',
    driverSkill: 5,
    notes: 'High scoring consistency. Handled minor mid-field bump gracefully without skipping a beat.',
    timestamp: '2026-09-23 14:22:40',
  },
  {
    id: 'scout-3',
    matchNumber: 43,
    teamNumber: 1323,
    scoutName: 'David K.',
    alliance: 'Blue',
    driverStation: 2,
    autoLeave: true,
    autoCoralL1: 0,
    autoCoralL2: 2,
    autoCoralL3: 2,
    autoCoralL4: 1,
    autoAlgaeProcessor: 2,
    autoAlgaeNet: 0,
    autoMissed: 1,
    teleopCoralL1: 2,
    teleopCoralL2: 3,
    teleopCoralL3: 4,
    teleopCoralL4: 3,
    teleopAlgaeProcessor: 2,
    teleopAlgaeNet: 2,
    cycles: 10,
    defenseRating: 3,
    climbStatus: 'Deep Cage',
    climbTimeSeconds: 6.0,
    diedOrTipped: false,
    cards: 'None',
    driverSkill: 4,
    notes: 'Heavy pushing power. Great intake recovery when algae rebounded.',
    timestamp: '2026-09-23 14:35:10',
  },
];

export const INITIAL_PIT_DATA: PitScoutingData[] = [
  {
    teamNumber: 254,
    scoutName: 'Lead Pit Scout',
    drivetrain: 'Swerve SDS Mk4i (L3 Ratio)',
    dimensions: '28 x 28 x 38 in',
    weightLbs: 119.5,
    motorsDrive: '4x Kraken X60',
    motorsSteer: '4x Falcon 500',
    intakeType: 'Under-bumper active motorized roller + pneumatic centering',
    scoringCapabilities: ['L1 Coral', 'L2 Coral', 'L3 Coral', 'L4 Coral', 'Algae Processor', 'Barge Net'],
    visionSystem: '2x Limelight 3G (Megatag2 pose estimation) + PhotonVision coprocessor',
    preferredAutonomous: '5-piece auto starting from center sub-station zone',
    climbCapability: 'Fast Deep Cage latch with passive ratcheting hooks',
    photoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
    pitNotes: 'Clean wire management. CAN FD bus topology with zero error frames. Battery swapping under 30 seconds.',
    inspectionPassed: true,
    batteryVoltage: 12.8,
    lastChecked: '2026-09-23 13:45',
  },
  {
    teamNumber: 1678,
    scoutName: 'Pit Lead Scout',
    drivetrain: 'Swerve SDS Mk4i (L3+ Ratio)',
    dimensions: '27.5 x 27.5 x 39 in',
    weightLbs: 121.0,
    motorsDrive: '4x Kraken X60',
    motorsSteer: '4x Falcon 500',
    intakeType: 'Over-bumper articulated intake with compliant polyurethane wheels',
    scoringCapabilities: ['L1-L4 Coral', 'Algae Processor', 'Net Thrower'],
    visionSystem: '3x Orange Pi 5 coprocessors running PhotonVision 240FPS',
    preferredAutonomous: '4-piece auto with adaptive path planner',
    climbCapability: 'Pneumatic assisted winch system for Deep Cage',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    pitNotes: 'Double bumper quick-latch system. All pneumatics tested to 120 PSI holding without leaks.',
    inspectionPassed: true,
    batteryVoltage: 12.9,
    lastChecked: '2026-09-23 13:50',
  },
  {
    teamNumber: 118,
    scoutName: 'NASA Scout',
    drivetrain: 'Custom Billet Aluminum Swerve',
    dimensions: '29 x 29 x 42 in',
    weightLbs: 124.0,
    motorsDrive: '4x Kraken X60 with FOC',
    motorsSteer: '4x NEO Vortex',
    intakeType: 'Floating telescopic intake arm with dual suction assist',
    scoringCapabilities: ['L1-L4 Coral', 'Algae Net Thrower'],
    visionSystem: 'Custom stereo vision camera with infrared ring illumination',
    preferredAutonomous: 'Center auto with defensive barrier avoidance',
    climbCapability: 'Telescoping carbon fiber arms with mechanical lock',
    photoUrl: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
    pitNotes: 'Exceptional aerospace craftsmanship. Gold anodized components throughout.',
    inspectionPassed: true,
    batteryVoltage: 12.7,
    lastChecked: '2026-09-23 14:00',
  },
];

export const INITIAL_PICKLIST: PicklistTeam[] = [
  {
    teamNumber: 254,
    rank: 1,
    role: 'First Pick',
    notes: 'Top tier scoring rate. Flawless autonomous routines and instant cycle alignment.',
    strengths: ['L4 Coral specialist', '5-piece Auto', 'Sub-5s climb', 'Elite driver pathing'],
    weaknesses: ['High profile target for heavy defense'],
    favoriteAlliancePartners: [1678, 2910],
    flaggedDNP: false,
  },
  {
    teamNumber: 1678,
    rank: 2,
    role: 'First Pick',
    notes: 'High reliability, adaptable to any alliance configuration. Excellent Algae management.',
    strengths: ['Multi-level coral scoring', 'Reliable Net shooter', 'Co-op specialist'],
    weaknesses: ['Slightly wider turning radius under heavy defense'],
    favoriteAlliancePartners: [254, 2056],
    flaggedDNP: false,
  },
  {
    teamNumber: 2056,
    rank: 3,
    role: 'First Pick',
    notes: 'Incredible cycle consistency in match playoffs. Very disciplined defense evasion.',
    strengths: ['Rapid teleop cycles', 'Stable bumper geometry', 'Experienced drive team'],
    weaknesses: ['Less variation in auto routes'],
    favoriteAlliancePartners: [254, 1323],
    flaggedDNP: false,
  },
  {
    teamNumber: 2910,
    rank: 4,
    role: 'Second Pick',
    notes: 'Elite maneuverability. Incredible synergy as a complementary feeder/scorer.',
    strengths: ['Agile swerve drive', 'Consistent L3/L4 conversion', 'Low center of gravity'],
    weaknesses: ['Slower deep cage latch time'],
    favoriteAlliancePartners: [254, 1678],
    flaggedDNP: false,
  },
  {
    teamNumber: 1323,
    rank: 5,
    role: 'Second Pick',
    notes: 'Heavy pushing power. Excellent secondary scorer and primary Algae clear agent.',
    strengths: ['Physical defense resilience', 'Strong intake recovery', 'High motor torque'],
    weaknesses: ['Higher CAN bus load observed in late matches'],
    favoriteAlliancePartners: [1678, 2056],
    flaggedDNP: false,
  },
];
